// AI Disclosure: This file may partially contain code generated by models such as GitHub Copiolot or ChatGPT
import { verifyRefreshToken, generateAccessToken } from '../../../utils/auth';;

export default async function handler(req, res) {
  if (req.method === 'POST') {
    const { refreshToken } = req.body;

    try {
      const decoded = verifyRefreshToken(refreshToken);

      if (!decoded) {
        return res.status(401).json({ error: 'Invalid refresh token' });
      }

      const newAccessToken = generateAccessToken({
        userId: decoded.userId,
        email: decoded.email,
      });

      return res.status(200).json({ accessToken: newAccessToken });
    } catch (error) {
      return res.status(500).json({ error: 'Error refreshing token' });
    }
  } else {
    return res.status(405).json({ error: 'Method not allowed' });
  }
}
