// AI Disclosure: This file may partially contain code generated by models such as GitHub Copiolot or ChatGPT
import { execute } from '../../../utils/executeLocal';

export default async function handler(req, res) {
    if (req.method === 'POST') {
        let { code, language, stdin } = req.body;
        if (code === undefined) {
            return res.status(400).json({ error: 'Code is required' });
        }
        if (language === "" || language === undefined) {
            return res.status(400).json({ error: 'Language is required' });
        }
        if (language !== "javascript" && language !== "python" && language !== "java" && language !== "c" && language !== "cpp") {
            return res.status(400).json({ error: 'Language not supported' });
        }
        if (stdin === undefined) {
            stdin = "";
        }

        try {
            const output = await execute(code, language, stdin);
            return res.status(200).json({ output });
        } catch (error) {
            console.error(error);
            return res.status(500).json({ error: 'Failed to execute code' });
        }

    } else {
        return res.status(405).json({ error: 'Method not allowed' });
    }
}