// AI Disclosure: This file may partially contain code generated by models such as GitHub Copiolot or ChatGPT
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
    // admin password 
  const hashedPassword = await bcrypt.hash(process.env.ADMINPASSWORD, 10); 

  const adminUser = await prisma.user.create({
    data: {
      firstName: 'Admin',
      lastName: 'Administrator',
      email: 'admin@admin.com',  
      password: hashedPassword,    // Store a hashed password
      role: 'ADMIN',               // Set role to ADMIN
    },
  });

  console.log('Admin user created:', adminUser);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
