// AI Disclosure: This file may partially contain code generated by models such as GitHub Copiolot or ChatGPT
export interface Preset {
    id: string
    name: string
  }
  
  export const presets: Preset[] = [
    {
      id: "1",
      name: "Hello world in Python",
    },
  ]